name: MLflow Experiment CI

on:
  push:
    branches:
      - main   # atau branch utama kamu

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install mlflow

    - name: Run MLflow experiment
      run: |
        mlflow run . --no-conda

    - name: Commit and push MLflow artifacts
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add mlruns/
        git commit -m "Add MLflow artifacts from CI"
        git push origin main
      env:
        # token otomatis tersedia di secrets GITHUB_TOKEN
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
