name: MLflow Experiment CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: titanic-env
          auto-activate-base: false

      - name: Install MLflow (>=2.19.0) and Docker SDK
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          pip install mlflow>=2.19.0 docker

      - name: Run MLflow experiment
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run . -P n_estimators=100 -P data_path=train_preprocessing.csv --env-manager=local
          # After running the MLflow experiment, get the latest run ID
          # This command lists directories in mlruns/0, sorts by time, and extracts the basename (the run ID)
          export LATEST_RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)
          echo "::set-output name=run_id::$LATEST_RUN_ID"
        id: run_mlflow_experiment # Add an ID to reference outputs

      - name: Commit and push MLflow artifacts
        shell: bash -l {0}
        run: |
          mkdir -p MLProject/mlruns # Ensure the directory exists
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add MLProject/mlruns/
          git commit -m "Add MLflow artifacts from CI" || echo "No changes to commit"
          git push origin main

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image from trained model
        shell: bash -l {0}
        run: |
          cd MLProject
          # Use the output from the previous step to get the correct RUN_ID
          export RUN_ID="${{ steps.run_mlflow_experiment.outputs.run_id }}"
          echo "Latest RUN_ID: $RUN_ID"
          mlflow models build-docker -m mlruns/0/$RUN_ID/artifacts/model -n mkarmand/mlflow-model:latest

      - name: Push Docker image to Docker Hub
        run: docker push mkarmand/mlflow-model:latest
